### PR TITLE
Add Defungify

### PR DESCRIPTION
**Pull request by the-emerald**
A set of smart contracts that let you package up ERC-20 tokens as NFTs (plus a message) and then they can be sent to other people like gift cards!

I have released this project as a public good so I make no profit from this.

### CODE REVIEW

**Comment by poria-cat** [comment]
@the-emerald Thanks for the submission, this looks really good, but there doesn't seem to be an image that could be used as a logo. Are you sure you don't want to put a logo?

**Comment by the-emerald** [comment]
Oops! Looks like for some reason the image wasn't added to the commit for some reason. Terribly sorry.

**Comment by poria-cat** [comment]
@the-emerald  Thank you again for your submission, it has been added and the Chinese translation has been changed to a more appropriate version.

**Comment by the-emerald** [comment]
Thank you very much!

**Pull request merged**
